export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_CART = 'GET_CART';
export const GET_FAVORITES = 'GET_FAVORITES';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const GET_COLLECTION_PRODUCTS = 'GET_COLLECTION_PRODUCTS';

export const GET_NEWS = 'GET_NEWS';

export const GET_COMPANY_INFORMATION = 'GET_COMPANY_INFORMATION';