export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_BESTSELLERS = 'GET_BESTSELLERS';
export const GET_LATEST = 'GET_LATEST';
export const GET_CART = 'GET_CART';
export const GET_FAVORITES = 'GET_FAVORITES';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const GET_COLLECTIONS_COUNT = 'GET_COLLECTIONS_COUNT';
export const GET_COLLECTION = 'GET_COLLECTION';
export const GET_COLLECTION_PRODUCTS = 'GET_COLLECTION_PRODUCTS';

export const GET_ABOUT = 'GET_ABOUT';
export const GET_ADVANTAGES = 'GET_ADVANTAGES';
export const GET_FOOTER = 'GET_FOOTER';
export const GET_HEADER = 'GET_HEADER';
export const GET_HELP = 'GET_HELP';
export const GET_NEWS = 'GET_NEWS';
export const GET_OFFER = 'GET_OFFER';
export const GET_SLIDER = 'GET_SLIDER';